server:
  servlet:
    context-path: /hms
  port: 8080

spring:
  application:
    name: hms
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.SQLServerDialect
  cloud:
    vault:
      kv:
        enabled: true
        backend: secret
        default-context: application
        profile-separator: '/'
      authentication: TOKEN
      token: hms@2026
      scheme: http
      host: 103.167.89.125
      port: 8200
  config:
    import: vault://

jwt:
  valid-duration: 6000 # in second
  refreshable-duration: 36000 # in seconds
springdoc:
  api-docs:
    path: /api-docs

temporal:
  connection:
    target: localhost:7233
  namespace: default